import React,{useEffect,useRef,useState} from 'react';
import {CONTACT_EMAIL} from '../data/links';
export function ContactModal({open,onClose}:{open:boolean;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);const [name,setName]=useState('');const [email,setEmail]=useState('');const [message,setMessage]=useState('');const [prepared,setPrepared]=useState(false);const [status,setStatus]=useState('');
 useEffect(()=>{if(open&&!ref.current?.open)ref.current?.showModal();else if(!open&&ref.current?.open)ref.current.close()},[open]);
 const brief=`Hello Angry Cactus,\n\nName: ${name}\nReply email: ${email}\n\n${message}`;
 const field='w-full bg-zinc-100 text-black border-2 border-black p-3 mt-2';
 return <dialog ref={ref} onCancel={onClose} onClose={onClose} aria-labelledby="contact-title" className="w-[calc(100%-32px)] max-w-xl max-h-[90vh] overflow-auto bg-white text-black border-4 border-black p-6 m-auto"><div className="flex justify-between items-center gap-4"><h2 id="contact-title" className="font-display text-4xl uppercase">Contact</h2><button type="button" onClick={onClose} aria-label="Close contact" className="border-2 border-black p-2">×</button></div><p className="my-5">Questions about an order or wholesale? Prepare a message for {CONTACT_EMAIL}. For a purchase, include the marketplace and order reference; never include payment details.</p><form className="space-y-4" onChange={()=>{setPrepared(false);setStatus('')}} onSubmit={e=>{e.preventDefault();setPrepared(true)}}><label className="block">Name<input className={field} required maxLength={80} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label className="block">Reply email<input className={field} required type="email" maxLength={150} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="block">Message<textarea className={field} required minLength={10} maxLength={600} rows={4} value={message} onChange={e=>setMessage(e.target.value)}/></label><button className="bg-black text-white p-4 font-bold">Prepare email →</button></form>{prepared&&<section className="mt-6 border-t-2 border-black pt-5"><h3 className="font-bold">Ready to review — not sent yet.</h3><p className="my-3">Send from your email app, or copy this text and email {CONTACT_EMAIL}.</p><pre className="whitespace-pre-wrap break-words text-sm p-3 bg-zinc-100">{brief}</pre><a className="inline-block bg-primary text-white p-3 mt-4" href={`mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent('Angry Cactus inquiry')}&body=${encodeURIComponent(brief)}`}>Open email app</a><button className="ml-4 underline" onClick={async()=>{try{await navigator.clipboard.writeText(brief);setStatus('Copied.')}catch{setStatus('Select and copy the text above.')}}}>Copy message</button></section>}<p role="status">{status}</p></dialog>
}
